import type { Property, Category } from '../types';

export const categories: Category[] = [
  {
    id: 'all',
    name: 'All',
    icon: 'https://ext.same-assets.com/121327883/1238042795.jpeg',
  },
  {
    id: 'cabins',
    name: 'Cabins',
    icon: 'https://ext.same-assets.com/121327883/1238042795.jpeg',
  },
  {
    id: 'amazing-views',
    name: 'Amazing views',
    icon: 'https://ext.same-assets.com/121327883/1268037615.jpeg',
  },
  {
    id: 'beach',
    name: 'Beachfront',
    icon: 'https://ext.same-assets.com/121327883/2938564312.jpeg',
  },
  {
    id: 'tiny-homes',
    name: 'Tiny homes',
    icon: 'https://ext.same-assets.com/121327883/3230373217.jpeg',
  },
  {
    id: 'countryside',
    name: 'Countryside',
    icon: 'https://ext.same-assets.com/121327883/3230373217.jpeg',
  },
  {
    id: 'mansions',
    name: 'Mansions',
    icon: 'https://ext.same-assets.com/121327883/3454955637.jpeg',
  },
  {
    id: 'castles',
    name: 'Castles',
    icon: 'https://ext.same-assets.com/121327883/421551827.jpeg',
  },
  {
    id: 'iconic-cities',
    name: 'Iconic cities',
    icon: 'https://ext.same-assets.com/121327883/421551827.jpeg',
  },
  {
    id: 'treehouses',
    name: 'Treehouses',
    icon: 'https://ext.same-assets.com/121327883/3807054935.jpeg',
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Lux Cabin | Mountain View, River, Hiking, Kayaking',
    description: 'The Buffalo River Chalet is a custom luxury cabin nestled on 40 acres that adjoins the federally protected and popular Buffalo National River. Perched high in the Ozark Mountains, this stay was meticulously crafted for those who enjoy immersing themselves in nature without forgoing modern comforts.',
    location: 'Compton, Arkansas',
    country: 'United States',
    price: 27532,
    images: [
      'https://ext.same-assets.com/3082894056/2729178818.jpeg',
      'https://ext.same-assets.com/3082894056/4271998597.jpeg',
      'https://ext.same-assets.com/3082894056/4266532394.jpeg',
      'https://ext.same-assets.com/3082894056/312226543.jpeg',
      'https://ext.same-assets.com/3082894056/2736819178.jpeg',
    ],
    category: 'cabins',
    type: 'Entire cabin',
    bedrooms: 2,
    bathrooms: 1,
    guests: 6,
    amenities: [
      'Kitchen',
      'Wifi',
      'Dedicated workspace',
      'Free parking on premises',
      'Private hot tub',
      'TV',
      'EV charger',
      'Washing machine',
    ],
    rating: 4.94,
    reviewCount: 32,
    host: {
      id: '101',
      name: 'Dustin',
      image: 'https://ext.same-assets.com/3082894056/2096761692.jpeg',
      isSuperhost: true,
    },
  },
  {
    id: '2',
    title: 'Cozy Penthouse-Style 1 BHK',
    description: 'A stunning penthouse-style apartment with modern amenities and spectacular views of the city.',
    location: 'Bengaluru',
    country: 'India',
    price: 7412,
    images: [
      'https://ext.same-assets.com/435899473/1562287212.jpeg',
    ],
    category: 'amazing-views',
    type: 'Apartment',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: [
      'Kitchen',
      'Wifi',
      'Air conditioning',
      'Dedicated workspace',
      'Free parking',
      'TV',
      'Washing machine',
    ],
    rating: 5.0,
    reviewCount: 35,
    host: {
      id: '102',
      name: 'Rahul',
      image: '',
      isSuperhost: true,
    },
  },
  {
    id: '3',
    title: 'Farm, Tiny House and a Lake!',
    description: 'Escape to this beautiful tiny house on a farm with a private lake. Perfect for a peaceful getaway.',
    location: 'Boppalapuram',
    country: 'India',
    price: 28751,
    images: [
      'https://ext.same-assets.com/435899473/1095387499.jpeg',
    ],
    category: 'tiny-homes',
    type: 'Farm stay',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: [
      'Lake access',
      'Kitchen',
      'Wifi',
      'Outdoor space',
      'Free parking',
      'Pets allowed',
    ],
    rating: 4.92,
    reviewCount: 137,
    host: {
      id: '103',
      name: 'Vijay',
      image: '',
      isSuperhost: true,
    },
  },
  {
    id: '4',
    title: 'Cozy Studio Apartment 4 @ Hole in the Wall Cafe',
    description: 'A beautiful studio apartment located right next to the popular Hole in the Wall Cafe. Perfect for tourists and business travelers.',
    location: 'Bengaluru',
    country: 'India',
    price: 14379,
    images: [
      'https://ext.same-assets.com/435899473/2074132307.jpeg',
    ],
    category: 'iconic-cities',
    type: 'Apartment',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: [
      'Kitchen',
      'Wifi',
      'Air conditioning',
      'Washing machine',
      'TV',
      'Essentials',
    ],
    rating: 4.92,
    reviewCount: 64,
    host: {
      id: '104',
      name: 'Priya',
      image: '',
      isSuperhost: false,
    },
  },
  {
    id: '5',
    title: 'Jo\'s Under The Sun Studio Pent',
    description: 'Beautiful penthouse studio with amazing city views and modern amenities.',
    location: 'Bengaluru',
    country: 'India',
    price: 25676,
    images: [
      'https://ext.same-assets.com/435899473/2130217919.jpeg',
    ],
    category: 'amazing-views',
    type: 'Guest suite',
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: [
      'Balcony',
      'Kitchen',
      'Wifi',
      'Air conditioning',
      'Dedicated workspace',
      'TV',
    ],
    rating: 5.0,
    reviewCount: 19,
    host: {
      id: '105',
      name: 'Jo',
      image: '',
      isSuperhost: true,
    },
  },
  {
    id: '6',
    title: 'EL Palm House Private Independent Home',
    description: 'A spacious and private independent home with plenty of outdoor space and modern amenities.',
    location: 'Bengaluru',
    country: 'India',
    price: 20256,
    images: [
      'https://ext.same-assets.com/435899473/2594707437.jpeg',
    ],
    category: 'countryside',
    type: 'Entire home',
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: [
      'Garden',
      'Kitchen',
      'Wifi',
      'Free parking',
      'Air conditioning',
      'TV',
      'Washing machine',
    ],
    rating: 4.94,
    reviewCount: 51,
    host: {
      id: '106',
      name: 'Elizabeth',
      image: '',
      isSuperhost: false,
    },
  },
  {
    id: '7',
    title: 'Street View 1BHK (AC in bedroom) in Koramangala',
    description: 'Modern apartment with amazing street views in the popular Koramangala neighborhood. Perfect for exploring the city.',
    location: 'Bengaluru',
    country: 'India',
    price: 13395,
    images: [
      'https://ext.same-assets.com/435899473/1309488341.jpeg',
    ],
    category: 'iconic-cities',
    type: 'Flat',
    bedrooms: 1,
    bathrooms: 1,
    guests: 3,
    amenities: [
      'Kitchen',
      'Wifi',
      'Air conditioning',
      'TV',
      'Washing machine',
      'Essentials',
    ],
    rating: 4.84,
    reviewCount: 70,
    host: {
      id: '107',
      name: 'Ravi',
      image: '',
      isSuperhost: false,
    },
  },
  {
    id: '8',
    title: 'Zen Bungalow Indiranagar (Solo Travelers)',
    description: 'A peaceful bungalow perfect for solo travelers in the trendy Indiranagar area.',
    location: 'Bengaluru',
    country: 'India',
    price: 7132,
    images: [
      'https://ext.same-assets.com/435899473/3880875968.jpeg',
    ],
    category: 'cabins',
    type: 'Room',
    bedrooms: 1,
    bathrooms: 1,
    guests: 1,
    amenities: [
      'Garden',
      'Wifi',
      'Air conditioning',
      'Kitchen',
      'Dedicated workspace',
    ],
    rating: 4.72,
    reviewCount: 196,
    host: {
      id: '108',
      name: 'Vartika',
      image: 'https://ext.same-assets.com/435899473/609882803.jpeg',
      isSuperhost: true,
    },
  },
];

export default {
  categories,
  mockProperties,
};
